name: "nllb-odia"

data:
  path: "ai4bharat/samanantar"
  source_lang: eng_Latn
  target_lang: ory_Orya
  dataset_config_name: "or"
  train_file: null
  valid_file: null
  test_file: null

model:
  name: "facebook/nllb-200-distilled-600M"
  use_lora: false
  lora:
    r: 8
    alpha: 32
    dropout: 0.05
    target_modules:
      - q_proj
      - v_proj

experiment:
  mode: rl_baseline
  name: rl_baseline_odia
  reward:
    type: baseline
    lambda1: 0.7
    lambda2: 0.2
    lambda3: 0.1
    lm_model: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
  s3_output_uri: ""
  upload_model_to_s3: false

training:
  lr: 0.000002
  accumulate_grad_batches: 1
  epochs: 3
  max_steps: 8000
  batch_size: 2
  num_return_sequences: 4
  updates_per_batch: 1
  gen_temperature: 1.8
  beta: 0.04
  clip_param: 0.2
  top_k: 100
  top_p: 0.95
  use_wandb: false
  log_every_n_steps: 5
  update_ref_policy_every_n_steps: 16

eval:
  run: true
  only: false
  translation_metric: ["bleu", "chrf++", "ter", "bertscore"]
  bertscore_lang: or
  every_n_opt_steps: 500
  num_beams: 1

test:
  run: true
  translation_metric: ["bleu", "chrf++", "ter", "bertscore"]
  bertscore_lang: or
  num_beams: 1

constraints:
  min_sentence_len: 1
  max_sentence_len: 63
